part of 'livraison_bloc.dart';

@freezed
class LivraisonState with _$LivraisonState {
  const factory LivraisonState(
      {bool? errorVille,
      bool? errorPointRecuperation,
      required bool isMapSelectedPointRecuperation,
      required int indexType1,
      // double? longitudeRecuperation,
      PointLivraisonModel? selected_recuperation_point,
      String? quartier_recuperation_point,
      String? paiement_url,
      List<VilleModel>? villeList,
      int? idColis,
      List<Colis>? listColis,
      List<File>? imageColis,
      List<PointLivraisonModel>? list_localisation_point,
      List<PointLivraisonModel>? list_search_point_localisation,
      VilleModel? selectedVIlle,
      TextEditingController? phone,
      TextEditingController? libelle,
      TextEditingController? contactEmetteur,
      TextEditingController? description,
      GlobalKey<FormState>? formKeyLivraison,
      GlobalKey<FormState>? formKeyColis,
      TextEditingController? nomColis,
      TextEditingController? quantiteColis,
      TextEditingController? contactRecepteur,
      TextEditingController? valeurColis,
      required TextEditingController libelleLocalisationRecuperation,
      required TextEditingController quartierRecuperation,
      required TextEditingController libelleLocalisationLivraison,
      required TextEditingController quartierLivraison,
      CategoryModel? categoryColis,
      List<CategoryModel>? list_category_colis,
      required bool isMapSelectedPointLivraison,
      PointLivraisonModel? selected_livraison_point,
      bool? errorCategory,
      bool? errorPointLivraison,
      int? isRequest,
      double? frais,
      bool? errorQte,
      int? isDownloadFacture,
      bool? errorImage,
      int? isLoadPLivraison,
      int? isLoadLivraison,
      int? isLoadVille,
      bool? isColisOK,
      bool? successLivraison,
      String? launchUrl,
      int? loadingMapPlaceInfo,
      MapPlaceInfoModel? mapPlaceInfo,
      int? isLoadVCategory,
      String? urlFacture,
      String? errorMessage,
      String? urlLivraison,
      List<LivraisonModel>? userLivraisonList,
      WebViewController? controller,
      LatLng? position,
      int? isLoadingPlaceSearch,
      int? currentLivraisonId,
      int? isLoadingPlaceSearchInfo,
      List<PlaceModel>? list_search_place,
      LatLng? findedPlaceInfo,
      ModePaiementModel? selectedModePaiement,
      ServiceModel? selectedService,
      required int indexType2,
      ConversationColisModel? conversationColis,
      int? isLoadingConversationColis,
      required List<LivreurLivraisonPositionModel> listLivreurLivraisonPosition,
      CurrentLivraisonPositionModel? currentLivraison,
      required bool findCurrentlyDelivery,
      required bool isCurrentlyDelivery}) = _LivraisonState;

  factory LivraisonState.initial() => LivraisonState(
        findCurrentlyDelivery: false,
        isCurrentlyDelivery: false,
        listLivreurLivraisonPosition: [],
        formKeyLivraison: GlobalKey<FormState>(),
        errorMessage: '',
        formKeyColis: GlobalKey<FormState>(),
        loadingMapPlaceInfo: 0,
        selectedModePaiement: null,
        currentLivraisonId: null,
        list_search_place: [],
        paiement_url: '',
        urlLivraison: '',
        findedPlaceInfo: null,
        selectedService: null,
        controller: null,
        mapPlaceInfo: null,
        isColisOK: false,
        isLoadingPlaceSearch: null,
        isLoadingPlaceSearchInfo: null,
        isLoadLivraison: 0,
        successLivraison: false,
        isMapSelectedPointLivraison: false,
        isMapSelectedPointRecuperation: false,
        errorVille: false,
        isLoadVille: 0,
        isLoadVCategory: 0,
        errorImage: false,
        isDownloadFacture: null,
        isRequest: 0,
        urlFacture: '',
        isLoadPLivraison: null,
        frais: 0,
        errorQte: false,
        errorPointRecuperation: false,
        errorCategory: false,
        errorPointLivraison: false,
        indexType1: 0,
        idColis: 1,
        listColis: [],
        userLivraisonList: [],
        launchUrl: null,
        imageColis: [],
        list_category_colis: [],
        list_localisation_point: [],
        list_search_point_localisation: [],
        villeList: [],
        phone: TextEditingController(),
        libelle: TextEditingController(),
        contactEmetteur: TextEditingController(),
        description: TextEditingController(),
        nomColis: TextEditingController(),
        quantiteColis: TextEditingController(text: '1'),
        contactRecepteur: TextEditingController(),
        valeurColis: TextEditingController(),
        indexType2: 0,
        libelleLocalisationRecuperation: TextEditingController(),
        quartierRecuperation: TextEditingController(),
        libelleLocalisationLivraison: TextEditingController(),
        quartierLivraison: TextEditingController(),
      );
}
