include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - 'flutter_downloader/**'
  errors:
      invalid_annotation_target: ignore
      depend_on_referenced_packages: ignore
      use_build_context_synchronously: ignore

linter:
  rules:
    prefer_single_quotes: true

