name: BabanaExpress
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+16
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  open_filex: ^4.4.0
  connectivity: ^3.0.6
  custom_navigation_bar: ^0.8.2
  flexible_text_editing_controller: ^1.0.0+2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_localization: ^0.2.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.4.0
  geolocator: ^10.1.0
  get_storage: ^2.1.1
  google_maps_flutter: ^2.2.8
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  intl_translation: ^0.20.0
  jwt_decode: ^0.3.1
  loading_indicator: ^3.1.1
  new_version_plus: ^0.0.11
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  screenshot: ^2.0.0
  share_plus: ^10.0.0
  # shimmer: ^3.0.0
  skeletonizer: ^1.3.0

  socket_io_client: ^2.0.3+1
  webview_flutter: ^4.2.3
  google_sign_in:
  file_picker: ^8.0.3

  auto_route: ^7.8.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  google_fonts: ^6.1.0
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.5
  dio: ^5.0.1
  crypto: ^3.0.1
  dartz: ^0.10.0
  responsive_framework: ^1.1.1
  rflutter_alert: ^2.0.4
  pretty_dio_logger: ^1.1.1
  flutter_phoenix: ^1.0.0
  flutter_dotenv: ^5.0.2
  flavor: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_rating_stars: ^1.0.3+4
  url_launcher:
  rxdart: ^0.27.7
  floating_action_bubble: ^1.1.4
  contacts_service: ^0.6.3
  fluttertoast: ^8.2.4
  flutter_animarker: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.1
  build_runner: "^2.1.4"
  freezed: ^2.0.3+1
  json_serializable: ^6.0.1
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  objectbox_generator: ^4.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
flutter:
  fonts:
    - family: Glastone
      fonts:
        - asset: assets/fonts/Glastone-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
  #   - family: coolvetica
  #     fonts:
  #       - asset: assets/fonts/coolvetica/coolvetica compressed hv.otf
  #       - asset: assets/fonts/coolvetica/coolvetica condensed rg.otf
  #       - asset: assets/fonts/coolvetica/coolvetica crammed rg.otf
  #       - asset: assets/fonts/coolvetica/coolvetica rg it.otf
  #       - asset: assets/fonts/coolvetica/coolvetica rga.otf

  #   - family: Helvetica
  #     fonts:
  #       - asset: assets/fonts/helvetica/Helvetica Black Condensed Oblique.otf
  #       - asset: assets/fonts/helvetica/Helvetica Black Condensed.otf
  #       - asset: assets/fonts/helvetica/Helvetica Black Oblique.otf
  #       - asset: assets/fonts/helvetica/helvetica black.otf
  #       - asset: assets/fonts/helvetica/Helvetica Bold Condensed.otf
  #       - asset: assets/fonts/helvetica/Helvetica Bold Narrow Oblique.otf
  #       - asset: assets/fonts/helvetica/Helvetica Condensed Bold Oblique.otf
  #       - asset: assets/fonts/helvetica/Helvetica Condensed Oblique.otf
  #       - asset: assets/fonts/helvetica/Helvetica Condensed Regular.ttf
  #       - asset: assets/fonts/helvetica/Helvetica Extra Compressed Regular.otf
  #       - asset: assets/fonts/helvetica/Helvetica Inserat Roman.otf
  #       - asset: assets/fonts/helvetica/Helvetica Light Condensed.otf
  #       - asset: assets/fonts/helvetica/Helvetica Roman.ttf
  #       - asset: assets/fonts/helvetica/Helvetica Rounded Black.otf
  #       - asset: assets/fonts/helvetica/Helvetica Rounded Bold Oblique.otf
  #       - asset: assets/fonts/helvetica/Helvetica Rounded Bold.otf
  #       - asset: assets/fonts/helvetica/Helvetica Rounded Condensed Bold.otf
  #       - asset: assets/fonts/helvetica/Helvetica Rounded LT Std Bold Condensed Oblique.otf
  #       - asset: assets/fonts/helvetica/Helvetica Ultra Compressed.otf
  #       - asset: assets/fonts/helvetica/Helvetica.ttf
  #       - asset: assets/fonts/helvetica/helvetica_condensed.ttf
  #       - asset: assets/fonts/helvetica/Helvetica-Bold Oblique.ttf
  #       - asset: assets/fonts/helvetica/Helvetica-Bold.ttf
  #       - asset: assets/fonts/helvetica/helvetica-compressed.otf
  #       - asset: assets/fonts/helvetica/helvetica-light.ttf
  #       - asset: assets/fonts/helvetica/Helvetica-LightOblique.ttf
  #       - asset: assets/fonts/helvetica/Helvetica-Narrow Bold.ttf
  #       - asset: assets/fonts/helvetica/Helvetica-Narrow Roman.ttf
  #       - asset: assets/fonts/helvetica/Helvetica-Narrow-Oblique.ttf
  #       - asset: assets/fonts/helvetica/Helvetica-Oblique.ttf
  #       - asset: assets/fonts/helvetica/helvetica-rounded-bold.otf

  uses-material-design: true

  assets:
    - assets/
    - assets/env/
    - assets/translations/
    - assets/images/
    - assets/logo/
    - assets/svg_icones/
    - assets/payement/
    # - assets/logo/logo.png
    # - assets/images/bg_white.jpeg
    # - assets/logo/logo.png
    # - assets/logo/logo_t1.svg
    # - assets/logo/logo_t2.svg
    # - assets/logo/logo_t3.svg
    # - assets/om.png
    # - assets/login.png
    # - assets/register.png
    # - assets/payement/om.png
    # - assets/payement/momo.png
    # - assets/payement/paycard.png
    # - assets/svg_icones/user.svg
    # - assets/svg_icones/callreceive.svg
    # - assets/svg_icones/mapTagUser.svg
    # - assets/svg_icones/onbo1.png
    # - assets/svg_icones/onbo2.png
    # - assets/svg_icones/onbo3.png
    # - assets/svg_icones/logImg.png
    # - assets/svg_icones/menu.svg
    # - assets/svg_icones/logUser1.svg
    # - assets/svg_icones/shoppingCart.svg
    # - assets/svg_icones/refresh.svg
    # - assets/svg_icones/home.svg
    # - assets/svg_icones/bagmoney.svg
    # - assets/svg_icones/phone_mobile.svg
    # - assets/svg_icones/key.svg
    # - assets/svg_icones/grid1.svg
    # - assets/svg_icones/grid2.svg
    # - assets/svg_icones/list0.svg
    # - assets/svg_icones/logo.svg
    # - assets/svg_icones/logo_without.svg
    # - assets/svg_icones/logo_esq.svg
    # - assets/svg_icones/play.svg
    # - assets/svg_icones/bell.svg
    # - assets/svg_icones/like.svg
    # - assets/svg_icones/story_boutique.svg
    # - assets/images/shop2.png
    # - assets/images/shop1.png
    # - assets/images/empty_shop.png
    # - assets/svg_icones/hand.svg
    # - assets/svg_icones/location.svg
    # - assets/svg_icones/nmreproduit.svg
    # - assets/svg_icones/setting.svg
    # - assets/svg_icones/produits.svg
    # - assets/svg_icones/short.svg
    # - assets/svg_icones/commandes.svg
    # - assets/svg_icones/ventes.svg
    # - assets/svg_icones/babana.svg
    # - assets/svg_icones/p3.svg
    # - assets/svg_icones/p2.svg
    # - assets/svg_icones/p1.svg
    # - assets/svg_icones/colis.svg
    # - assets/svg_icones/wallet.svg
