name: BananaExpress
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+8
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6
  custom_navigation_bar: ^0.8.2
  flexible_text_editing_controller: ^1.0.0+2
  flutter:
    sdk: flutter
  flutter_local_notifications: null
  flutter_localization: ^0.2.0
  flutter_spinkit: any
  flutter_svg: any
  font_awesome_flutter: ^10.4.0
  geolocator: ^10.1.0
  get_storage: any
  google_maps_flutter: ^2.2.8
  image_cropper: any
  image_gallery_saver: null
  image_picker: any
  intl: null
  intl_phone_field: ^3.2.0
  intl_translation: any
  jwt_decode: null
  loading_indicator: ^3.1.1
  new_version_plus: ^0.0.11
  objectbox: ^2.2.1
  objectbox_flutter_libs: any
  path_provider: any
  pdf: any
  permission_handler: any
  pinput: any
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  screenshot: ^2.0.0
  share_plus: ^7.1.0
  shimmer: ^3.0.0
  socket_io_client: any
  syncfusion_flutter_pdf: ^22.2.10
  toast: ^0.3.0
  uni_links: ^0.5.1
  webview_flutter: ^4.2.3

  auto_route: ^7.8.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  google_fonts: ^6.1.0
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.5
  dio: ^5.0.1
  crypto: ^3.0.1
  dartz: ^0.10.0
  responsive_framework: ^1.1.1
  rflutter_alert: ^2.0.4
  pretty_dio_logger: ^1.1.1
  flutter_phoenix: ^1.0.0
  flutter_dotenv: ^5.0.2
  flavor: ^2.0.0

  flutter_rating_stars: ^1.0.3+4
  intl_phone_number_input: ^0.7.3+1
  focus_detector: ^2.0.1
  fluttertoast: ^8.2.2

  equatable: ^2.0.5
  image: ^4.1.3
  rxdart: ^0.27.7 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.1
  build_runner: "^2.1.4"
  freezed: ^2.0.3+1
  json_serializable: ^6.0.1
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  objectbox_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf

  uses-material-design: true

  assets:
    - assets/env/
    - assets/translations/
    - assets/images/
    - assets/svg_icones/
    - assets/logo/logo.png
    - assets/images/bg_white.jpeg
    - assets/logo/logo.png
    - assets/om.png
    - assets/login.png
    - assets/register.png
    - assets/payement/om.png
    - assets/payement/momo.png
    - assets/payement/paycard.png
    - assets/svg_icones/user.svg
    - assets/svg_icones/callreceive.svg
    - assets/svg_icones/mapTagUser.svg
    - assets/svg_icones/onbo1.png
    - assets/svg_icones/onbo2.png
    - assets/svg_icones/onbo3.png
    - assets/svg_icones/logImg.png
    - assets/svg_icones/menu.svg
    - assets/svg_icones/logUser1.svg
    - assets/svg_icones/shoppingCart.svg
    - assets/svg_icones/refresh.svg
    - assets/svg_icones/home.svg
    - assets/svg_icones/bagmoney.svg
    - assets/svg_icones/phone_mobile.svg
    - assets/svg_icones/key.svg
    - assets/svg_icones/grid1.svg
    - assets/svg_icones/grid2.svg
    - assets/svg_icones/list0.svg
    - assets/svg_icones/logo.svg
    - assets/svg_icones/logo_without.svg
    - assets/svg_icones/logo_esq.svg
    - assets/svg_icones/play.svg
    - assets/svg_icones/bell.svg
    - assets/svg_icones/like.svg
    - assets/svg_icones/story_boutique.svg
    - assets/images/shop2.png
    - assets/images/shop1.png
    - assets/images/empty_shop.png
    - assets/svg_icones/hand.svg
    - assets/svg_icones/location.svg
    - assets/svg_icones/nmreproduit.svg
    - assets/svg_icones/setting.svg
    - assets/svg_icones/produits.svg
    - assets/svg_icones/short.svg
    - assets/svg_icones/commandes.svg
    - assets/svg_icones/ventes.svg
    - assets/svg_icones/babana.svg
