part of 'market_bloc.dart';

@freezed
class MarketState with _$MarketState {
  const factory MarketState({
    bool? errorVille,
    bool? errorPointRecuperation,
    String? paiement_url,
    List<VilleModel>? villeList,
    int? idProduit,
    List<ProduitModel>? listProduits,
    List<PanierModel>? paniers,
    List<File>? imageProduit,
    VilleModel? selectedVIlle,
    TextEditingController? quantiteProduit,
    TextEditingController? contactRecepteur,
    CategoryModel? category,
    required bool isMapSelectedPointLivraison,
    PointLivraisonModel? selected_livraison_point,
    bool? errorCategory,
    bool? errorPointLivraison,
    int? isRequest,
    double? frais,
    bool? errorQte,
    required int indexCarossel,
    int? isDownloadFacture,
    bool? errorImage,
    int? isLoadedPLivraison,
    int? isLoadedLivraison,
    int? isLoadedVille,
    bool? successLivraison,
    String? launchUrl,
    int? loadingMapPlaceInfo,
    int? isLoadedProduit,
    MapPlaceInfoModel? mapPlaceInfo,
    int? isLoadedVCategory,
    String? urlFacture,
    List<LivraisonMarketModel>? userLivraisonList,
    WebViewController? controller,
    LatLng? position,
    int? isLoadingPlaceSearch,
    int? isLoadingPlaceSearchInfo,
    GlobalKey<FormState>? formKeyLivraison,
    ModePaiementModel? selectedModePaiement,
  }) = _MarketState;

  factory MarketState.initial() => MarketState(
        formKeyLivraison: GlobalKey<FormState>(),
        paniers: [],
        indexCarossel: 0,
        isLoadedProduit: 0,
        loadingMapPlaceInfo: 0,
        selectedModePaiement: null,
        paiement_url: '',
        controller: null,
        isLoadingPlaceSearch: null,
        isLoadingPlaceSearchInfo: null,
        isLoadedLivraison: 0,
        successLivraison: false,
        isMapSelectedPointLivraison: false,
        errorVille: false,
        isLoadedVille: 0,
        isLoadedVCategory: 0,
        errorImage: false,
        isDownloadFacture: null,
        isRequest: 0,
        urlFacture: '',
        isLoadedPLivraison: null,
        frais: 0,
        errorQte: false,
        errorPointRecuperation: false,
        errorCategory: false,
        errorPointLivraison: false,
        idProduit: 1,
        listProduits: [],
        userLivraisonList: [],
        launchUrl: null,
        quantiteProduit: TextEditingController(text: '1'),
        contactRecepteur: TextEditingController(),
      );
}
